apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mac2000/argo-self
    targetRevision: HEAD
    path: "."
    directory:
      recurse: true
      include: "*/application.yml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true # otherwise can not delete apps
      selfHeal: true
