apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
  labels:
    name: app2
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: mactemp1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  revisionHistoryLimit: 3
  project: default
  info:
    - name: "Example:"
      value: "https://example.com"
  source:
    repoURL: https://github.com/mac2000/argo-self
    targetRevision: HEAD
    path: app2
  destination:
    server: https://kubernetes.default.svc
    namespace: default # dev, test2, production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
