apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - image: nginx:alpine
          name: app2
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 600m
          volumeMounts:
            - name: app2
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: app2
          configMap:
            name: app2
