apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - issuer.yaml
  - certificate.yaml
  - ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: argocd-repo-server.yaml
  - path: argocd-cm.yml
  - path: argocd-rbac-cm.yml
  - path: argocd-cmd-params-cm.yml
  - path: argocd-server.yml
  - path: argocd-notifications-secret.yml
  - path: argocd-notifications-cm.yml
# https://github.com/argoproj/argoproj-deployments/blob/master/argocd/overlays/production/argo-cd-cm.yaml

commonLabels:
  app: argo
commonAnnotations:
  owner: marchenko.alexandr@gmail.com
  repository: https://github.com/mac2000/argo-self

configMapGenerator:
  - name: argocd-styles-cm
    files:
      - robota.css

generatorOptions:
  disableNameSuffixHash: true
# kubectl kustomize argo
# kubectl apply -k argo
